FROM tomcat:8.0-jre8
MAINTAINER Tim Dudgeon <tdudgeon@informaticsmatters.com>

RUN echo JAVA_OPTS='"-Dcom.squonk.keycloak.baseurl=$KEYCLOAK_SERVER_URL"' > /usr/local/tomcat/bin/setenv.sh
RUN rm -rf /usr/local/tomcat/webapps/*

# copy the keycloak jars to the tomcat lib folder
RUN curl -o keycloak.zip https://downloads.jboss.org/keycloak/2.5.5.Final/adapters/keycloak-oidc/keycloak-tomcat8-adapter-dist-2.5.5.Final.zip && unzip -d /usr/local/tomcat/lib/ keycloak.zip && rm keycloak.zip 

ADD build/libs/example-java-servlet.war        /usr/local/tomcat/webapps/ROOT.war
RUN unzip -d /usr/local/tomcat/webapps/ROOT /usr/local/tomcat/webapps/ROOT.war && rm -f /usr/local/tomcat/webapps/ROOT.war

COPY openshift/keycloak/web.xml openshift/keycloak/keycloak.json /usr/local/tomcat/webapps/ROOT/WEB-INF/
COPY openshift/keycloak/context.xml openshift/keycloak/tomcat-users.xml openshift/keycloak/server.xml openshift/keycloak/logging.properties /usr/local/tomcat/conf/

# remove unused or conflicting jars
#RUN cd /usr/local/tomcat/webapps/portal/WEB-INF/lib && rm commons-codec-*.jar commons-logging-*.jar httpclient*.jar httpcore*.jar\
# keycloak*.jar jackson-annotations-*.jar jackson-core-*.jar jackson-databind-*.jar servlet-api-3.0.jar


RUN useradd -u 501 -m -g root tomcat && chown -R tomcat:root /usr/local/tomcat
RUN chown -R tomcat:root /usr/local/tomcat

USER 501
 
EXPOSE 8080
