apiVersion: v1
kind: Template
metadata:
  name: example-java-servlet
  annotations:
    description: "Java servlet example"
    iconClass: "icon-tomcat"
    tags: "servlet,java,openrisknet"
labels:
  template: example-java-servlet
message: "Example servlet has been deployed."  
objects:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: example-java-servlet
  spec:
    replicas: 1  
    selector:    
      name: example-java-servlet
    template:    
      metadata:
        labels:  
          name: example-java-servlet 
      spec:
        containers:
        - image: openrisknet/example-java-servlet
          name: example-java-servlet
          env:
          - name: GREETING
            value: ${GREETING}
          ports:
          - containerPort: 8080
            protocol: TCP
          securityContext:
          - runAsUser: MustRunAsNonRoot
        restartPolicy: Always

parameters:
- description: The text for the greeting
  name: GREETING
  value: Hello