apiVersion: v1
kind: Template
metadata:
  name: service
  annotations:
    description: "Java servlet example"
    iconClass: "icon-tomcat"
    tags: "servlet,java,openrisknet"
labels:
  app: hello-servlet
  template: deploy-hello-servlet
message: "Example servlet has been deployed."

objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
  spec:
    replicas: 1  
    selector:    
      name: ${APP_NAME}
    template:    
      metadata:
        labels:  
          name: ${APP_NAME}
      spec:
        containers:
        - image: tdudgeon/hello-example-servlet
          name: ${APP_NAME}
          env:
          - name: GREETING
            value: ${GREETING}
          ports:
          - containerPort: 8080
            protocol: TCP
          securityContext:
          - runAsUser: MustRunAsNonRoot
          volumeMounts:
          - mountPath: /usr/local/tomcat/conf/context.xml
            name: ${APP_NAME}-sso-config
            subPath: context.xml
            readOnly: true
          - mountPath: /usr/local/tomcat/webapps/ROOT/WEB-INF/keycloak.json
            name: ${APP_NAME}-sso-config
            subPath: keycloak.json
            readOnly: true
        restartPolicy: Always
        volumes:
          - name: ${APP_NAME}-sso-config
            configMap:
              name: ${APP_NAME}-sso-config

- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP	  

- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_NAME}
    annotations:
      kubernetes.io/tls-acme: "false"
  spec:
    host: ${APPLICATION_DOMAIN}
    port:
      targetPort: http
    to: 
      name: ${APP_NAME}
      kind: Service
    tls:
      termination: edge

parameters:
- name: APP_NAME
  description: Application name
  value: hello-servlet
- name: GREETING
  description: The text for the greeting
  value: Hello
- name: APPLICATION_DOMAIN
  description: "The exposed hostname that will route to the service, if left blank a value will be defaulted."
  value: ""
